### ISSUE TITLE
can i change the colour?

### ISSUE THREAD

**Issue by muslichwr** [derSeppo/rubiks-cube#1]
can u share how to change the colour mate?

**Comment by derSeppo** [comment]
Sure!
So previously the color of the sides had fixed values of light and dark red, green and blue based on the inital position and orientation of the faces, so you couldn't really change them.
However I just pushed a new version with the correct cube colors and the possibility to change them to any value you want via the color array in the CubeletRenderer.h file.

Hope that helps!
